## WCUS Trips cleaning steps
Get the data [here](https://ndclibrary.sec.usace.army.mil/resource?title=2023%20WCUS%20Trips%20-%20All%20Regions%20&documentId=07ddf14b-1522-4c6f-d894-40cd74d58a7f).

1. Filter to get only In/Out/Thru=="Outbound Shipping" or "Inbound Shipping"
2. Filter to get only TrafficCode==1 (aka TrafficName=="Domestic (Trips & Drafts)")
3. Keep only the columns:
    * 'RegionName', 'Up/Down', 'VesselType', 'VesselTypeName', 'VesselDraftFt', 'Trips', 'CompletedYear'
4. Create a few separate data sets: 
    * Filter to get only WaterwayCode==3924 (aka WaterwayName=="Duluth-Superior, MN and WI")
    * Filter to get only RegionName=="GREAT LAKES"
5. Save as something descriptive like "WCUS_Trips_DuluthSuperior_Outbound_Domestic_2014-2023.csv"

## List of Top Iron Ore Outports and Inports

In [5]:
import pandas as pd

In [55]:
# No Thunder Bay. That is in ON.
# Taconite and Silver Bay (last two) are not USACE ports
outports = pd.DataFrame({
    'WaterwayCode':[3924, 3926, 3619, 3844]#, 3929, 3928]
    })

In [56]:
# Note also:
# Cleveland-Cliffs Dearborn Works in Michigan
# Great Lakes Steel in Michigan
# These facilities ultimately receive taconite by rail, though

# Make sure to distinguish between receipts and throughports
    # E.g. Chicago is just a rail hub, other places go straight to mills nearby
# Calumet and Chicago included at end just because Calumet is high-tonnage and Chicago is famous
# Not much iron ore though
inports = pd.DataFrame({
    'WaterwayCode': [3738, 3736, 3739, 3204, 3217, 3315, 3220, 3219, 3741, 3747]
    })

## WCUS Trips Cleaning

In [23]:
path = "../data/raw/Trips_AllRegions_10yr_2014-2023.xlsx"

wcus = pd.read_excel(path, sheet_name="Trips_AllRegions_10yr_2014-2023")

In [24]:
# pd.set_option('display.max_rows', None)
# wcus.loc[:, ['WaterwayCode', 'WaterwayName']].drop_duplicates()

In [57]:
wcus.merge(outports, how='right').loc[:, ['WaterwayName', 'WaterwayCode']].drop_duplicates()
# wcus.loc[wcus['WaterwayCode'].isin(outports['WaterwayCode']), 'WaterwayName'].unique()

                    WaterwayName  WaterwayCode
0     Duluth-Superior, MN and WI          3924
1152             Two Harbors, MN          3926
1752   Presque Isle Township, MI          3619
2597        Marquette Harbor, MI          3844

In [41]:
# wcus.merge(inports, how='right')['WaterwayName'].unique()
wcus.loc[wcus['WaterwayCode'].isin(inports['WaterwayCode']), 'WaterwayName'].unique()

array(['Ashtabula Port Authority, OH', 'Burns Waterway Harbor, IN',
       'Calumet Harbor and River, IL and IN', 'Chicago Harbor, IL',
       'Cleveland-Cuyahoga Port, OH', 'Conneaut Harbor, OH', 'Gary, IN',
       'Indiana Harbor, IN', 'Rouge River, MI',
       'Toledo-Lucas County Port, OH'], dtype=object)

In [ ]:
cols_keep = ['WaterwayCode', 'WaterwayName', 'In/Out/Thru', 'VesselType', 'VesselTypeName']

In [39]:
# TODO
# Now filter then aggregate into chart-ready CSVs
wcus.loc[
        wcus['WaterwayCode'].isin(outports['WaterwayCode']) 
            & wcus['VesselTypeName'].isin(['Dry Cargo Barge', 'Self-Propelled dry'])
            & wcus['VesselTypeName'].isin(['Dry Cargo Barge', 'Self-Propelled dry'])
            & (wcus['In/Out/Thru'] == 'Outbound Shipping')
            & (wcus['TrafficCode'] == 1) # Domestic (Trips & Drafts)
            ,
        :
    ]

,RegionName,WaterwayCode,WaterwayName,TrafficCode,TrafficName,In/Out/Thru,Up/Down,VesselType,VesselTypeName,VesselDraftFt,Trips,CompletedYear
149342,GREAT LAKES,3924,"Duluth-Superior, MN and WI",1,Domestic (Trips & Drafts),Outbound Shipping,Port,4.0,Dry Cargo Barge,2,481,2014
149343,GREAT LAKES,3924,"Duluth-Superior, MN and WI",1,Domestic (Trips & Drafts),Outbound Shipping,Port,4.0,Dry Cargo Barge,2,274,2015
149344,GREAT LAKES,3924,"Duluth-Superior, MN and WI",1,Domestic (Trips & Drafts),Outbound Shipping,Port,4.0,Dry Cargo Barge,2,184,2016
149345,GREAT LAKES,3924,"Duluth-Superior, MN and WI",1,Domestic (Trips & Drafts),Outbound Shipping,Port,4.0,Dry Cargo Barge,2,95,2017
149346,GREAT LAKES,3924,"Duluth-Superior, MN and WI",1,Domestic (Trips & Drafts),Outbound Shipping,Port,4.0,Dry Cargo Barge,2,120,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
203053,GREAT LAKES,3926,"Two Harbors, MN",1,Domestic (Trips & Drafts),Outbound Shipping,Port,1.0,Self-Propelled dry,31,1,2019
203054,GREAT LAKES,3926,"Two Harbors, MN",1,Domestic (Trips & Drafts),Outbound Shipping,Port,1.0,Self-Propelled dry,31,1,2020
203055,GREAT LAKES,3926,"Two Harbors, MN",1,Domestic (Trips & Drafts),Outbound Shipping,Port,1.0,Self-Propelled dry,31,8,2021
203056,GREAT LAKES,3926,"Two Harbors, MN",1,Domestic (Trips & Drafts),Outbound Shipping,Port,1.0,Self-Propelled dry,31,13,2022
203057,GREAT LAKES,3926,"Two Harbors, MN",1,Domestic (Trips & Drafts),Outbound Shipping,Port,1.0,Self-Propelled dry,31,7,2023

## WCUS Cargo cleaning steps

1. Filter to only WaterwayCodes in `inports` and `outports`

## WCUS Cargo cleaning

In [5]:
path = "../data/raw/Cargo_AllRegions_10yr_2013-2022.xlsx"

cargo = pd.read_excel(path, sheet_name="Cargo_AllRegions_10yr_2013-2022")

In [ ]:
cargo.loc[
    cargo['WaterwayCode']==outports.iloc[0, 0], 
    :
]

,WaterwayCode,WaterwayName,TrafficCode,TrafficName,CommodityCode,CommodityName,Allo1Code,In/Out/Thru,Allo2Code,Up/Down,ShortTons,TonMiles,CompletedYear
269619,3924,"Duluth-Superior, MN and WI",11,Overseas Imports,3219,Other Hydrocarbons,1,Inbound Receiving,0,Port,97,0,2021
269620,3924,"Duluth-Superior, MN and WI",11,Overseas Imports,3220,Alcohols,1,Inbound Receiving,0,Port,83,0,2021
269621,3924,"Duluth-Superior, MN and WI",11,Overseas Imports,3230,Carboxylic Acids,1,Inbound Receiving,0,Port,5691,0,2021
269622,3924,"Duluth-Superior, MN and WI",11,Overseas Imports,3275,"Inorg. Elem., Oxides, & Halogen Salts",1,Inbound Receiving,0,Port,83,0,2021
269623,3924,"Duluth-Superior, MN and WI",11,Overseas Imports,3275,"Inorg. Elem., Oxides, & Halogen Salts",1,Inbound Receiving,0,Port,6,0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...
270004,3924,"Duluth-Superior, MN and WI",70,Intraport,4322,Limestone,3,Local,0,Port,7850,0,2020
270005,3924,"Duluth-Superior, MN and WI",70,Intraport,4331,Sand & Gravel,3,Local,0,Port,102204,0,2022
270006,3924,"Duluth-Superior, MN and WI",70,Intraport,4335,Waterway Improv. Mat,3,Local,0,Port,17250,0,2017
270007,3924,"Duluth-Superior, MN and WI",70,Intraport,4410,Iron Ore,3,Local,0,Port,10560,0,2013
270008,3924,"Duluth-Superior, MN and WI",70,Intraport,4410,Iron Ore,3,Local,0,Port,19878,0,2022

In [6]:
cargo.head()

,WaterwayCode,WaterwayName,TrafficCode,TrafficName,CommodityCode,CommodityName,Allo1Code,In/Out/Thru,Allo2Code,Up/Down,ShortTons,TonMiles,CompletedYear
0,10,"Isle Au Haut Thoroughfare, ME",30,Coastwise,7900,Manufac. Prod. NEC,1,Inbound Receiving,1,Upbound/East/North,599,599,2013
1,10,"Isle Au Haut Thoroughfare, ME",30,Coastwise,7900,Manufac. Prod. NEC,1,Inbound Receiving,1,Upbound/East/North,659,659,2014
2,10,"Isle Au Haut Thoroughfare, ME",30,Coastwise,7900,Manufac. Prod. NEC,1,Inbound Receiving,1,Upbound/East/North,623,623,2015
3,10,"Isle Au Haut Thoroughfare, ME",30,Coastwise,7900,Manufac. Prod. NEC,1,Inbound Receiving,1,Upbound/East/North,574,574,2016
4,10,"Isle Au Haut Thoroughfare, ME",30,Coastwise,7900,Manufac. Prod. NEC,1,Inbound Receiving,1,Upbound/East/North,703,703,2017